#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

echo ""
echo " BEANSTALKD_VERSION: ${BEANSTALKD_VERSION}"
echo " BUILD_DATE        : ${BUILD_DATE}"
echo " GIT_SHA1          : ${GIT_SHA1}"
echo ""

docker buildx bake image-all --push
